stages:
  - test

unittest:
  stage: test
  image: python:3.11
  script:
    - pip install spacy
    - pip install pytest==7.4.3
    - pip install coverage pytest-cov
    - python -m spacy download en_core_web_md
    - python -m pytest
    - coverage run --source=. --omit='*/test_*.py,*_test.py,*__init__.py' -m pytest
    - coverage report -m

  coverage: /(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
